# Generated by Django 4.2.13 on 2024-05-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='descriptions',
            field=models.TextField(verbose_name='Сообшение'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='fio',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
    ]
