# Generated by Django 4.2.13 on 2024-11-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_type_user_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='user/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='video', verbose_name='Фото для обложки'),
        ),
    ]
