# Generated by Django 5.1.3 on 2024-11-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_alter_type_img_alter_user_img_alter_video_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='img',
            field=models.ImageField(blank=True, upload_to='video', verbose_name='Фото для обложки'),
        ),
    ]
